name: Deploy Infra

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:
    inputs:
      destroy:
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:

  deploy-incedo:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: incedo-infra

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -reconfigure \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="key=terraform/incedo-infra.tfstate" \
          -backend-config="region=${AWS_REGION}"
      - run: terraform plan -var-file=incedo-infra.tfvars
      - run: terraform apply -auto-approve -var-file=incedo-infra.tfvars


  deploy-nttdata:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: nttdata-infra

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -reconfigure \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="key=nttdata/nttdata-infra.tfstate" \
          -backend-config="region=${AWS_REGION}"
      - run: terraform plan -var-file=nttdata-infra.tfvars
      - run: terraform apply -auto-approve -var-file=nttdata-infra.tfvars
